DROP TABLE IF EXISTS STOPS_LINES CASCADE;
DROP TABLE IF EXISTS STOPS_COURSES CASCADE;
DROP TABLE IF EXISTS USERS_ROLES CASCADE;
DROP TABLE IF EXISTS USERS_TRIPS CASCADE;
DROP TABLE IF EXISTS BOOKED CASCADE;
DROP TABLE IF EXISTS TRIPS CASCADE;
DROP TABLE IF EXISTS STOPS CASCADE;
DROP TABLE IF EXISTS ROLES CASCADE;
DROP TABLE IF EXISTS VEHICLES CASCADE;
DROP TABLE IF EXISTS USERS CASCADE;
DROP TABLE IF EXISTS LINES CASCADE;
DROP TABLE IF EXISTS COURSES CASCADE;

CREATE TABLE STOPS
(
    STOP_ID   BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    STOP_NAME VARCHAR(255)                        NOT NULL,
    PRIMARY KEY (STOP_ID)
);

CREATE TABLE LINES
(
    LINE_ID   BIGINT      NOT NULL GENERATED ALWAYS AS IDENTITY,
    LINE_NAME VARCHAR(10) NOT NULL,
    PRIMARY KEY (LINE_ID)
);

CREATE TABLE STOPS_LINES
(
    STOPS_LINES_ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
    LINE_ID BIGINT NOT NULL,
    STOP_ID BIGINT NOT NULL,
    ORDINAL INT NOT NULL,
    PRIMARY KEY (STOPS_LINES_ID),
    CONSTRAINT STOPS_LINES_FK_STOP FOREIGN KEY (STOP_ID) REFERENCES STOPS (STOP_ID),
    CONSTRAINT STOPS_LINES_FK_LINE FOREIGN KEY (LINE_ID) REFERENCES LINES (LINE_ID)
);

CREATE TABLE COURSES
(
    COURSE_ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
    LINE_ID   BIGINT NOT NULL,
    ORDINAL   INT    NOT NULL,
    PRIMARY KEY (COURSE_ID),
    CONSTRAINT COURSES_FK_LINE FOREIGN KEY (LINE_ID) REFERENCES LINES (LINE_ID)
);

CREATE TABLE STOPS_COURSES
(
    STOPS_COURSES_ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
    COURSE_ID BIGINT NOT NULL,
    STOP_ID   BIGINT NOT NULL,
    ESTIMATED TIME   NOT NULL,
    PRIMARY KEY (STOPS_COURSES_ID),
    CONSTRAINT STOPS_COURSES_FK_STOP FOREIGN KEY (STOP_ID) REFERENCES STOPS (STOP_ID),
    CONSTRAINT STOPS_COURSES_FK_LINE FOREIGN KEY (COURSE_ID) REFERENCES COURSES (COURSE_ID)
);

CREATE TABLE USERS
(
    USER_ID  BIGINT                NOT NULL GENERATED ALWAYS AS IDENTITY,
    PASSWORD VARCHAR(255)          NOT NULL,
    USERNAME VARCHAR(255)          NOT NULL UNIQUE,
    ENABLED  BOOLEAN DEFAULT FALSE NOT NULL,
    PRIMARY KEY (USER_ID)
);

CREATE TABLE ROLES
(
    ROLE_ID   BIGINT       NOT NULL,
    ROLE_NAME VARCHAR(255) NOT NULL,
    PRIMARY KEY (ROLE_ID)
);

CREATE TABLE USERS_ROLES
(
    USER_ROLES_ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
    USER_ID BIGINT NOT NULL,
    ROLE_ID BIGINT NOT NULL,
    PRIMARY KEY(USER_ROLES_ID),
    CONSTRAINT USERS_ROLES_FK_USER FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID),
    CONSTRAINT USERS_ROLES_FK_ROLE FOREIGN KEY (ROLE_ID) REFERENCES ROLES (ROLE_ID)
);

CREATE TABLE VEHICLES
(
    VEHICLE_ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
    CAPACITY   INT    NOT NULL,
    USER_ID    BIGINT NOT NULL,
    PRIMARY KEY (VEHICLE_ID),
    CONSTRAINT VEHICLES_FK_USER FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID)
);

CREATE TABLE TRIPS
(
    TRIP_ID    BIGINT      NOT NULL GENERATED ALWAYS AS IDENTITY,
    COURSE_ID  BIGINT      NOT NULL,
    VEHICLE_ID BIGINT      NOT NULL,
    OCCUPIED   BOOLEAN     NOT NULL DEFAULT FALSE,
    STATUS     varchar(10) NOT NULL,
    ESTIMATED_START_TIME TIMESTAMP NOT NULL,
    ESTIMATED_END_TIME TIMESTAMP NOT NULL,
    PRIMARY KEY (TRIP_ID),
    CONSTRAINT TRIPS_FK_COURSE FOREIGN KEY (COURSE_ID) REFERENCES COURSES (COURSE_ID),
    CONSTRAINT TRIPS_FK_VEHICLE FOREIGN KEY (VEHICLE_ID) REFERENCES VEHICLES (VEHICLE_ID)
);

CREATE TABLE USERS_TRIPS
(
    USER_TRIPS_ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
    TRIP_ID BIGINT NOT NULL,
    USER_ID BIGINT NOT NULL,
    PRIMARY KEY (USER_TRIPS_ID),
    CONSTRAINT USERS_TRIPS_FK_TRIP FOREIGN KEY (TRIP_ID) REFERENCES TRIPS (TRIP_ID),
    CONSTRAINT USERS_TRIPS_FK_USER FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID)
);

CREATE TABLE BOOKED(
                       BOOKED_ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
                       USER_ID BIGINT,
                       VEHICLE_ID BIGINT,
                       TRIP_ID BIGINT,
                       START_TIME TIMESTAMP NOT NULL,
                       END_TIME TIMESTAMP NOT NULL,
                       PRIMARY KEY (BOOKED_ID),
                       CONSTRAINT BOOKED_FK_VEHICLE FOREIGN KEY (VEHICLE_ID) REFERENCES VEHICLES (VEHICLE_ID),
                       CONSTRAINT BOOKED_FK_USER FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID),
                       CONSTRAINT BOOKED_FK_TRIP FOREIGN KEY (TRIP_ID) REFERENCES TRIPS (TRIP_ID)
)
