-- DROP TABLE STOPS_LINES CASCADE;
-- DROP TABLE STOPS_COURSES CASCADE;
-- DROP TABLE USERS_ROLES CASCADE;
-- DROP TABLE USERS_TRIPS CASCADE;
-- DROP TABLE TRIPS CASCADE;
-- DROP TABLE STOPS CASCADE;
-- DROP TABLE ROLES CASCADE;
-- DROP TABLE USERS CASCADE;
-- DROP TABLE LINES CASCADE;
-- DROP TABLE COURSES CASCADE;

CREATE TABLE STOPS
(
    STOP_ID   BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    STOP_NAME VARCHAR(255)                        NOT NULL,
    PRIMARY KEY (STOP_ID)
);

CREATE TABLE LINES
(
    LINE_ID   BIGINT      NOT NULL GENERATED ALWAYS AS IDENTITY,
    LINE_NAME VARCHAR(10) NOT NULL,
    PRIMARY KEY (LINE_ID)
);

CREATE TABLE STOPS_LINES
(
    LINE_ID BIGINT NOT NULL,
    STOP_ID BIGINT NOT NULL,
    CONSTRAINT FK_STOP FOREIGN KEY (STOP_ID) REFERENCES STOPS (STOP_ID),
    CONSTRAINT FK_LINE FOREIGN KEY (LINE_ID) REFERENCES LINES (LINE_ID)
);

CREATE TABLE COURSES
(
    COURSE_ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
    LINE_ID   BIGINT NOT NULL,
    ORDINAL   INT    NOT NULL,
    PRIMARY KEY (COURSE_ID),
    CONSTRAINT FK_LINE FOREIGN KEY (LINE_ID) REFERENCES LINES (LINE_ID)
);

CREATE TABLE STOPS_COURSES
(
    COURSE_ID BIGINT NOT NULL,
    STOP_ID   BIGINT NOT NULL,
    ESTIMATED TIME   NOT NULL,
    CONSTRAINT FK_STOP FOREIGN KEY (STOP_ID) REFERENCES STOPS (STOP_ID),
    CONSTRAINT FK_LINE FOREIGN KEY (COURSE_ID) REFERENCES COURSES (COURSE_ID)
);

CREATE TABLE USERS
(
    USER_ID  BIGINT                NOT NULL GENERATED ALWAYS AS IDENTITY,
    PASSWORD VARCHAR(255)          NOT NULL,
    USERNAME VARCHAR(255)          NOT NULL UNIQUE,
    ENABLED  BOOLEAN DEFAULT FALSE NOT NULL,
    PRIMARY KEY (USER_ID)
);

CREATE TABLE ROLES
(
    ROLE_ID   BIGINT       NOT NULL,
    ROLE_NAME VARCHAR(255) NOT NULL,
    PRIMARY KEY (ROLE_ID)
);

CREATE TABLE USERS_ROLES
(
    USER_ID BIGINT NOT NULL,
    ROLE_ID BIGINT NOT NULL,
    CONSTRAINT FK_USER FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID),
    CONSTRAINT FK_ROLE FOREIGN KEY (ROLE_ID) REFERENCES ROLES (ROLE_ID)
);

CREATE TABLE VEHICLES
(
    VEHICLE_ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
    CAPACITY   INT    NOT NULL,
    USER_ID    BIGINT NOT NULL,
    PRIMARY KEY (VEHICLE_ID),
    CONSTRAINT FK_USER FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID)
);

CREATE TABLE TRIPS
(
    TRIP_ID    BIGINT      NOT NULL GENERATED ALWAYS AS IDENTITY,
    COURSE_ID  BIGINT      NOT NULL,
    VEHICLE_ID BIGINT      NOT NULL,
    OCCUPIED   BOOLEAN     NOT NULL DEFAULT FALSE,
    STATUS     varchar(10) NOT NULL,
    PRIMARY KEY (TRIP_ID),
    CONSTRAINT FK_COURSE FOREIGN KEY (COURSE_ID) REFERENCES COURSES (COURSE_ID),
    CONSTRAINT FK_VEHICLE FOREIGN KEY (VEHICLE_ID) REFERENCES VEHICLES (VEHICLE_ID)
);

CREATE TABLE USERS_TRIPS
(
    TRIP_ID BIGINT NOT NULL,
    USER_ID BIGINT NOT NULL,
    CONSTRAINT FK_TRIP FOREIGN KEY (TRIP_ID) REFERENCES TRIPS (TRIP_ID),
    CONSTRAINT FK_USER FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID)
);